#pragma once

#include <lvgl.h>

#if defined(CONFIG_PROSPECTOR_STATUS_SCREEN_CLASSIC)

LV_FONT_DECLARE(Symbols_Bold_26);
LV_FONT_DECLARE(Symbols_Regular_28);
LV_FONT_DECLARE(Symbols_Semibold_32);
LV_FONT_DECLARE(FG_Medium_20);
LV_FONT_DECLARE(FG_Medium_24);
LV_FONT_DECLARE(FR_Regular_48);
LV_FONT_DECLARE(FR_Thin_48);
LV_FONT_DECLARE(DINishCondensed_SemiBold_22);

#elif defined(CONFIG_PROSPECTOR_STATUS_SCREEN_RADII)

LV_FONT_DECLARE(Symbols_Semibold_32);
LV_FONT_DECLARE(Symbols_Semibold_28);
LV_FONT_DECLARE(Symbols_Medium_28);
LV_FONT_DECLARE(Symbols_Regular_28);
LV_FONT_DECLARE(Symbols_Bold_26);
LV_FONT_DECLARE(PPF_NarrowThin_64);
LV_FONT_DECLARE(DINishCondensed_SemiBold_22);
LV_FONT_DECLARE(DINishCondensed_SemiBold_20);

#elif defined(CONFIG_PROSPECTOR_STATUS_SCREEN_FIELD)

LV_FONT_DECLARE(Symbols_Semibold_32);
LV_FONT_DECLARE(Symbols_Regular_28);
LV_FONT_DECLARE(Symbols_Bold_26);
LV_FONT_DECLARE(FR_Regular_30);
LV_FONT_DECLARE(FR_Regular_36);
LV_FONT_DECLARE(FG_Medium_26);
LV_FONT_DECLARE(DINishCondensed_SemiBold_20);

#elif defined(CONFIG_PROSPECTOR_STATUS_SCREEN_OPERATOR)

LV_FONT_DECLARE(Symbols_Bold_20);
LV_FONT_DECLARE(Symbols_Bold_26);
LV_FONT_DECLARE(Symbols_Regular_28);
LV_FONT_DECLARE(FG_Medium_20);
LV_FONT_DECLARE(FG_Medium_21);
LV_FONT_DECLARE(FG_Medium_26);
LV_FONT_DECLARE(DINishExpanded_Light_25);
LV_FONT_DECLARE(DINishExpanded_Light_36);
LV_FONT_DECLARE(DINishCondensed_SemiBold_20);
LV_FONT_DECLARE(FR_Medium_22);
LV_FONT_DECLARE(FR_Medium_32);
LV_FONT_DECLARE(DINish_Medium_24);

#elif defined(CONFIG_PROSPECTOR_STATUS_SCREEN_GOSSIP)

/* Flying keys, one per perspective step, and the layer name */
LV_FONT_DECLARE(DINish_SemiBold_12);
LV_FONT_DECLARE(DINish_SemiBold_14);
LV_FONT_DECLARE(DINish_SemiBold_16);
LV_FONT_DECLARE(DINish_SemiBold_18);
LV_FONT_DECLARE(DINish_SemiBold_21);
LV_FONT_DECLARE(DINish_SemiBold_24);
LV_FONT_DECLARE(DINish_SemiBold_28);
LV_FONT_DECLARE(DINish_SemiBold_32);
LV_FONT_DECLARE(DINish_SemiBold_34);
LV_FONT_DECLARE(DINish_SemiBold_36);
LV_FONT_DECLARE(DINish_SemiBold_38);
LV_FONT_DECLARE(DINish_SemiBold_40);
LV_FONT_DECLARE(DINish_SemiBold_43);
LV_FONT_DECLARE(DINish_SemiBold_45);
LV_FONT_DECLARE(DINish_SemiBold_48);
LV_FONT_DECLARE(DINish_SemiBold_51);
LV_FONT_DECLARE(DINish_SemiBold_54);
LV_FONT_DECLARE(DINish_SemiBold_57);
LV_FONT_DECLARE(DINish_SemiBold_61);
LV_FONT_DECLARE(DINish_SemiBold_65);
LV_FONT_DECLARE(DINish_SemiBold_68);
LV_FONT_DECLARE(DINish_SemiBold_72);
LV_FONT_DECLARE(DINishCondensed_SemiBold_14);

#endif
